// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByQixjNpiqmfspHFxDUgCvdb3T04jKBKo',
    appId: '1:763397293299:web:8887929a31c13ba79b2386',
    messagingSenderId: '763397293299',
    projectId: 'daily-activities-9111d',
    authDomain: 'daily-activities-9111d.firebaseapp.com',
    storageBucket: 'daily-activities-9111d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6TbPRk7wM3HtH3WSs1KeoZ1hlhjcTDuc',
    appId: '1:763397293299:android:a82837ea5f6507bf9b2386',
    messagingSenderId: '763397293299',
    projectId: 'daily-activities-9111d',
    storageBucket: 'daily-activities-9111d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjqUkC99ILugMPstBv5kaoBFA-pdY_W2s',
    appId: '1:763397293299:ios:2b5baf9b372f022a9b2386',
    messagingSenderId: '763397293299',
    projectId: 'daily-activities-9111d',
    storageBucket: 'daily-activities-9111d.appspot.com',
    iosClientId: '763397293299-9nirlflhnejv10k6v8hck6rcr4i09uhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyactivitie',
  );
}
